# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Front-Ended
tagline:             'Swimming in the deep sea of front-end dev'
description:         'A blog about my adventures in learning to code.'
url:                 http://robinelon.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Robin Elon
  url:               https://twitter.com/robinelon
  email:             robinelon@gmail.com

# Custom vars
version:             1.0.0
